all: task_02 sum concat max

task_02: task_02.c
	gcc -Wall -o main task_02.c

sum: sum.c
	gcc -Wall -o sum sum.c

concat: concat.c
	gcc -Wall -o concat concat.c

max: max.c
	gcc -Wall -o max max.c

clean:
	rm -f task_02 sum concat max