all: sender receiver snifer

sender: task_14_sender.c
	gcc -Wall -o sender task_14_sender.c

receiver: task_14_receiver.c
	gcc -Wall -o receiver task_14_receiver.c

snifer: task_17_snifer.c
	gcc -Wall -o snifer task_17_snifer.c
clean:
	sender receiver snifer